@ECHO OFF
::env\Scripts\activate
ECHO -----------------------------------------
ECHO Runing flake8...
ECHO -----------------------------------------
env\Scripts\flake8.exe main.py
env\Scripts\flake8.exe app\__init__.py
env\Scripts\flake8.exe app\controllers\__init__.py
env\Scripts\flake8.exe app\controllers\average_age_by_career.py
env\Scripts\flake8.exe app\controllers\base_controller.py
env\Scripts\flake8.exe app\controllers\careers_by_average_age.py
env\Scripts\flake8.exe app\controllers\city_with_more_careers.py
env\Scripts\flake8.exe app\controllers\students_by_age.py
env\Scripts\flake8.exe app\controllers\students_by_average_age.py
env\Scripts\flake8.exe app\controllers\students_by_city.py
env\Scripts\flake8.exe app\controllers\students_by_country.py
env\Scripts\flake8.exe app\controllers\students_cities_residence.py
env\Scripts\flake8.exe app\decorators\__init__.py
env\Scripts\flake8.exe app\helpers\__init__.py
env\Scripts\flake8.exe app\helpers\csv_helper.py
env\Scripts\flake8.exe app\helpers\dict_helper.py
env\Scripts\flake8.exe app\helpers\export_helper.py
env\Scripts\flake8.exe app\helpers\json_helper.py
env\Scripts\flake8.exe app\helpers\screen_helper.py
env\Scripts\flake8.exe app\helpers\table_helper.py
env\Scripts\flake8.exe app\models\__init__.py
env\Scripts\flake8.exe app\models\average_age_by_career.py
env\Scripts\flake8.exe app\models\base_model.py
env\Scripts\flake8.exe app\models\careers_by_average_age.py
env\Scripts\flake8.exe app\models\city_with_more_careers.py
env\Scripts\flake8.exe app\models\data.py
env\Scripts\flake8.exe app\models\students_by_age.py
env\Scripts\flake8.exe app\models\students_by_average_age.py
env\Scripts\flake8.exe app\models\students_by_city.py
env\Scripts\flake8.exe app\models\students_by_country.py
env\Scripts\flake8.exe app\models\students_cities_residence.py
env\Scripts\flake8.exe app\tests\__init__.py
env\Scripts\flake8.exe app\views\__init__.py
env\Scripts\flake8.exe app\views\average_age_by_career.py
env\Scripts\flake8.exe app\views\base_view.py
env\Scripts\flake8.exe app\views\careers_by_average_age.py
env\Scripts\flake8.exe app\views\city_with_more_careers.py
env\Scripts\flake8.exe app\views\students_by_age.py
env\Scripts\flake8.exe app\views\students_by_average_age.py
env\Scripts\flake8.exe app\views\students_by_city.py
env\Scripts\flake8.exe app\views\students_by_country.py
env\Scripts\flake8.exe app\views\students_cities_residence.py
pause